### ISSUE TITLE
Unable to Clone

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [opendns/dataviz#1]
After running:

`git clone https://github.com/opendns/dataviz.git --recursive`

The following output:

`Cloning into 'raindance'...`
`fatal: unable to connect to github.com:`
`github.com[0: 192.30.252.131]: errno=Connection refused`
`Clone of 'git://github.com/ThibaultReuille/raindance.git' into submodule path 'raindance' failed`

Please either change the URL's in dataviz/.gitmodules from `git://` to `https://` or instruct uses to run the following before cloning the repo:

`git config --global url."https://".insteadOf git://`

**Comment by ThibaultReuille** [comment]
Fixed. Can you try again ?
