### ISSUE TITLE
Makefile Bugs (OpenGL/OpenCL Dependencies?)

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [opendns/dataviz#2]
After running the following in the `dataviz/graphiti` directory:

`make native`

The following output:

`In file included from ../raindance/Raindance.hh:3:`
`../raindance/Core/Headers.hh:18:12: fatal error: 'CL/cl.h' file not found`
`#  include <CL/cl.h>`

A similar error was also part of the output before installing the freeglut3 package. I'm assuming the OpenGL and OpenCL frameworks need to be properly installed before using dataviz. Please reflect this in both the homepage and the git repo/README.

**Comment by achillean** [comment]
On Ubuntu install the headers with:

apt-get install opencl-headers

I'm still unable to compile it on Ubuntu using clang++ but the above should solve that issue.

**Comment by 0xdeadbeefJERKY** [comment]
More errors after installing the OpenCL header files...

`In file included from Main.cc:5:
In file included from .//Graphiti.hh:8:
In file included from .//Core/Console.hh:9:
In file included from /usr/include/python2.7/Python.h:58:
/usr/include/python2.7/pyport.h:873:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
`

**Comment by andrewsmhay** [comment]
Thibault says that he has some fixes to push for Ubuntu. Will be up Monday at the latest.

**Comment by naumek** [comment]
Hello,
another problem on Ubuntu. After running

``` javascript
make native
```

I get error like

``` javascript
   --- Packing Resources ---
mkdir -p Pack
mkdir -p Pack/hud
xxd -i Resources/Hud/pointer.png > Pack/Hud/pointer.png
/bin/sh: 1: cannot create Pack/Hud/pointer.png: Directory nonexistent
make: *** [pack] Error 2
```

Script stops but file pointer.png exists in Pack/Hud directory...

**Comment by 0xdeadbeefJERKY** [comment]
You have to change the line "mkdir -p Pack/hud" to "mkdir -p Pack/Hud"
(Linux directories are case-sensitive).

**Comment by achillean** [comment]
That bug is actually already fixed in the latest version of graphiti, but the dataviz repository is referencing an old version. I recommend checking out the raindance/ graphiti repositories directly and not following the references from the dataviz repo.

**Comment by ThibaultReuille** [comment]
Thank you achillean. Sorry for replying to this so late. I've made a couple of fixes for Ubuntu, you should be able to compile just fine now.
