### ISSUE TITLE
So close, but yet...

### ISSUE THREAD

**Issue by mirrorgleam** [opendns/dataviz#3]
Over the past 8 hours I've been able to bang my head off the keyboard and finally got to the UI, Huzaa!  Now, how do I make it display any kind of data.  When I click on the add random graph button it shows that it's doing something but... nothing ever comes of it.  When I input "./graphiti demo" there are no nodes displayed.

My questions are: what type of file does this use to create the nodes, and is there an example one for use as a template?

Further clarification: I've looked into the /dataviz/graphiti/Scripts folder and cat'ed out the files in there looking for any clue to what should be producing the visualization, but so far no dice.

I'm also aware of the dataviz/semanticnet/examples folder but I'm unable to find a way to use these to produce a pretty web either.

Update:  So I'm able to make it show the nodes and edges for the sample data "cc-20140624-2200-DE.json" and the other.  Now the last thing I need to know how to do is use semanticnet to create graphable data from my own logs.  Any assistance with this would be appreciated.  Until then I'm going to keep banging my head against it like I've been doing and hope positive results are produced.

Thanks

**Comment by ThibaultReuille** [comment]
Hi Mirrorgleam,

> Over the past 8 hours I've been able to bang my head off the keyboard and finally got to the UI, Huzaa! 

Damn ! Well that's great I suppose ;) What were you struggling with ? Anything we could change to prevent that from happening in the future ?

> what type of file does this use to create the nodes, and is there an example one for use as a template?

Check out the screenshot included here, it shows a very basic example on how to create a graph, some nodes and connect them with different edges. For more advanced examples, you can check out the semanticnet wiki : https://github.com/ThibaultReuille/semanticnet/wiki

![screen shot 2014-08-14 at 3 38 32 pm](https://cloud.githubusercontent.com/assets/686506/3928042/cae45840-2403-11e4-9b0b-bc59a06d60d3.png)

>  Now the last thing I need to know how to do is use semanticnet to create graphable data from my own logs.

It highly depends on what you are trying to achieve. What kind of logs are you parsing ? What relational data do you want to represent ?

Also, I should mention that we just opened two google groups, checkout the links on the Support section of our Website.
http://www.opengraphiti.com/#support-or-contact
It's pretty empty right now but feel free to start a conversation to get ideas and feedback from the others ;)

Hope this helps,

**Comment by mirrorgleam** [comment]
A large portion of my issues probably stem from being handed a Mac for the first time then being told "I saw this awesome tool at Blackhat called openGraphiti, Google it and make it work for us."  So, I've never compiled a program or used the Git repositories or any of the steps required to make this work.  I'm attributing my inability to get this to work more to my lack of experience than to your program. 

What I've been asked to do:  turn pcap into pretty visual net.  
Where I'm at in this process:  I'm able to do most of the steps in the process so far, I believe. 

I can convert the http.log in the ~/dataviz/semanticnet/examples/sample folder to http.json which can be used in graphiti to make the pretty visual net.  I'm able to gather pcap and I'm under the impression that I can use bro -r (http://www.bro.org/) to convert the pcap file to a .log file, then use ./bro_graph.py to turn the .log into a .json file which can be read by ./graphiti.  My current (and hopefully last) fight is with Bro. I'm receiving this error:  "fatal error: can't find base/init-bare.bro". 

Once I get this issue resolved I'll be in business, I think.

Thanks for getting back to me.  :smile:
