### ISSUE TITLE
git clone with recursive fails.

### ISSUE THREAD

**Issue by tabithabragg** [opendns/dataviz#6]
# git clone  https://github.com/opendns/dataviz.git --recursive

Cloning into 'dataviz'...
remote: Counting objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (132/132), 13.29 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Submodule 'graphiti' (https://github.com/ThibaultReuille/graphiti.git) registered for path 'graphiti'
Submodule 'raindance' (https://github.com/ThibaultReuille/raindance.git) registered for path 'raindance'
Submodule 'semanticnet' (https://github.com/ThibaultReuille/semanticnet.git) registered for path 'semanticnet'
Cloning into 'graphiti'...
remote: Counting objects: 966, done.
remote: Total 966 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (966/966), 33.96 MiB | 3.26 MiB/s, done.
Resolving deltas: 100% (412/412), done.
Checking connectivity... done.
Submodule path 'graphiti': checked out '12561765d34a82e17b3b3120cbe31a01d76d0b9c'
Cloning into 'raindance'...
remote: Counting objects: 5684, done.
remote: Total 5684 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (5684/5684), 71.04 MiB | 6.94 MiB/s, done.
Resolving deltas: 100% (2397/2397), done.
Checking connectivity... done.
Submodule path 'raindance': checked out '5d90b1bf12130ca9dbaab54546539bb9a5db088f'
Cloning into 'semanticnet'...
remote: Counting objects: 653, done.
remote: Total 653 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (653/653), 776.19 KiB | 0 bytes/s, done.
Resolving deltas: 100% (407/407), done.
Checking connectivity... done.
fatal: reference is not a tree: 32c32a3a7b9300140007be948e6afa183d155338
Unable to checkout '32c32a3a7b9300140007be948e6afa183d155338' in submodule path 'semanticnet'

**Comment by ThibaultReuille** [comment]
Resolved.
